create table projects( 
	id integer primary key generated by default as identity,
	name text not null check (name <> ''),
	priority integer not null,
	deliverydate date not null
);

create table tasks(
	id integer primary key generated by default as identity,
	name text not null check (name <> ''), -- no vacio
	done boolean,
	projectId integer references projects(id)
);

select * from projects

insert into projects(name, priority, deliverydate, description)
values ('Making a apirest', 1, '2021-04-04', 'Using express')

insert into projects(name, priority, deliverydate, description)
values ('Making a refactoring', 1, '2021-04-04', 'Using routes')

insert into projects(name, priority, deliverydate, description)
values ('Testing new version of routes', 1, '2021-04-04', 'Using express')

select * from tasks

insert into tasks(name, done, projectId)
values('Donwload node', false, 1)

insert into tasks(name, done, projectId)
values('Desing UI', false, 2)

insert into tasks(name, done, projectId)
values('Make Coffe', false, 2)

